def shared_pods
  use_frameworks!
  pod 'KingfisherWebP', :path => '../'
end

target 'KingfisherWebP_Tests' do
  platform :ios, '8.0'
  shared_pods
end

target 'KingfisherWebP-iOS' do
  platform :ios, '8.0'
  shared_pods
end

target 'KingfisherWebP-watchOS' do
  platform :watchos, '2.0'
  shared_pods
end

target 'KingfisherWebP-tvOS' do
  platform :tvos, '9.0'
  shared_pods
end
